---
title: "result_soc"
author: "Qi"
date: "2023-08-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(reticulate)
library(keras)
library(tensorflow)
library(sp)
library(fields)
library(FRK)
```



# CRPS Calculation

```{r}
loss_all <- read.csv(here::here("us_soc/soc_loss.csv"))

us_soc <- read.csv(here::here("us_soc/soc.csv"))

long <- us_soc$long
lat <- us_soc$lat
y <- us_soc$soc

library(verification)
calculate_dist_between <- function(x){
  return( mean(spDists(matrix(x, ncol = 1)))  )
}

calculate_dist_true <- function(x, true_x){

  return( abs(x-true_x) )

}

crps <- function(prediction_matrix, true_value){
  print("Calculating between-sample distance . . .")
  between_sample <- apply(prediction_matrix, 1, calculate_dist_between)
  print("Calculating absolute error . . .")

  sample_residual <- rowMeans(apply(prediction_matrix, 2, calculate_dist_true, true_x = true_value))

  res <- 0.5 * between_sample - sample_residual
  return(-res)
}

pred_dnn <- as.matrix(read.csv("D:/77/Reasearch/temp/dnn_pred_soc.csv"))
pred_dk <- as.matrix(read.csv("D:/77/Reasearch/temp/dk_pred_soc.csv"))
pred_ck <- as.matrix(read.csv("D:/77/Reasearch/temp/ck_pred_soc.csv"))
pred_inla <- as.matrix(read.csv("D:/77/Reasearch/temp/inla_pred_soc.csv"))



crps_dnn_all <- crps(pred_dnn,y)
crps_dk_all <- crps(pred_dk,y)
crps_ck_all <- crps(pred_ck,y)
crps_inla_all <- crps(pred_inla,y)

# write.csv(crps_dnn_all,"D:/77/Reasearch/temp/crps_dnn_soc.csv",row.names = FALSE)
# write.csv(crps_dk_all,"D:/77/Reasearch/temp/crps_dk_soc.csv",row.names = FALSE)
# write.csv(crps_ck_all,"D:/77/Reasearch/temp/crps_ck_soc.csv",row.names = FALSE)
# write.csv(crps_inla_all,"D:/77/Reasearch/temp/crps_inla_soc.csv",row.names = FALSE)

crps_dnn_all <- as.matrix(read.csv("D:/77/Reasearch/temp/crps_dnn_soc.csv"))
crps_dk_all <- as.matrix(read.csv("D:/77/Reasearch/temp/crps_dk_soc.csv"))
crps_ck_all <- as.matrix(read.csv("D:/77/Reasearch/temp/crps_ck_soc.csv"))
crps_inla_all <- as.matrix(read.csv("D:/77/Reasearch/temp/crps_inla_soc.csv"))

print(paste("CRPS of DNN is: ", mean(crps_dnn_all)))
print(paste("CRPS of DK is: ", mean(crps_dk_all)))
print(paste("CRPS of CK is: ", mean(crps_ck_all)))
print(paste("CRPS of INLA is: ", mean(crps_inla_all)))

```


# Interval Score Calculation

```{r}
int_score <- function(l,u,true_x,alpha = 0.05){
  out_1 <- u-l
  out_2 <- 2/alpha * (l-true_x) * ifelse(true_x < l, 1, 0)
  out_3 <- 2/alpha * (true_x-u) * ifelse(true_x > u, 1, 0)
  return(out_1 + out_2 + out_3)
}

all_interval_score <- function(prediction_sample, alpha = 0.05, true_x){
  num_all <- length(true_x)
 pb <- txtProgressBar(min = 0,      # Minimum value of the progress bar
                     max = num_all, # Maximum value of the progress bar
                     style = 3,    # Progress bar style (also available style = 1 and style = 2)
                     width = 50,   # Progress bar width. Defaults to getOption("width")
                     char = "=")   # Character used to create the bar
 
  
  all_score <- rep(NA, length(true_x))
 for (int_score_idx in 1:length(true_x)) {
   setTxtProgressBar(pb, int_score_idx)
    l <- quantile(prediction_sample[int_score_idx,], alpha/2)
    u <- quantile(prediction_sample[int_score_idx,], 1-alpha/2)
    all_score[int_score_idx] <- int_score(l = l, u = u, true_x = true_x[int_score_idx], alpha = alpha)
  }
 return(all_score)
}

int_score_dnn <- all_interval_score(prediction_sample = pred_dnn, true_x = y)
int_score_dk <- all_interval_score(prediction_sample = pred_dk, true_x = y)
int_score_ck <- all_interval_score(prediction_sample = pred_ck, true_x = y)
int_score_inla <- all_interval_score(prediction_sample = pred_inla, true_x = y)


# write.csv(int_score_dnn,"D:/77/Reasearch/temp/int_dnn_soc.csv",row.names = FALSE)
# write.csv(int_score_dk,"D:/77/Reasearch/temp/int_dk_soc.csv",row.names = FALSE)
# write.csv(int_score_ck,"D:/77/Reasearch/temp/int_ck_soc.csv",row.names = FALSE)
# write.csv(int_score_inla,"D:/77/Reasearch/temp/int_inla_soc.csv",row.names = FALSE)


print(paste("Interval Score of DNN is: ", mean(int_score_dnn)))
print(paste("Interval Score of DK is: ", mean(int_score_dk)))
print(paste("Interval Score of CK is: ", mean(int_score_ck )))
print(paste("Interval Score of INLA is: ", mean(int_score_inla )))

```
```{r}



icr_inla <- sum( y>apply(pred_inla, 1,quantile, 0.025) & y<apply(pred_inla, 1,quantile, 0.975) )/length(y)
icr_dnn <- sum( y>apply(pred_dnn, 1,quantile, 0.025) & y<apply(pred_dnn, 1,quantile, 0.975) )/length(y)
icr_dk <- sum( y>apply(pred_dk, 1,quantile, 0.025) & y<apply(pred_dk, 1,quantile, 0.975) )/length(y)
icr_ck <- sum( y>apply(pred_ck, 1,quantile, 0.025) & y<apply(pred_ck, 1,quantile, 0.975) )/length(y)



score_tab <- 
  rbind(
    
    apply(loss_all, 2, mean)
    ,
    apply(cbind(crps_inla_all,crps_dnn_all,crps_dk_all,crps_ck_all),2, mean)
    ,
    matrix(c(icr_inla, icr_dnn, icr_dk, icr_ck), nrow = 1)
    ,
    apply(cbind(int_score_inla,int_score_dnn,int_score_dk,int_score_ck),2, mean)
  )

rownames(score_tab) <- c("MSE", "Negative CRPS", "ICR", "Interval Score")
colnames(score_tab) <- c("INLA","Base DNN", "DK","CK")


#xtable::xtable(t(round(score_tab,2)),aline = "c")

knitr::kable(round(score_tab,3))

```


